name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: Pranshu23x
          outputs: |
            dist/github-snake.svg?color_snake=#00FF00&color_dots=#1a1a2e,#00b300,#00cc00,#00e600,#00FF00
            dist/github-snake-dark.svg?color_snake=#00FF00&color_dots=#1a1a2e,#00b300,#00cc00,#00e600,#00FF00

      - name: Push output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          keep_files: true
